# NumPy Creating Arrays
NumPy is used to work with arrays. The array object in NumPy is called ndarray

In [8]:
import numpy as np

#Array Creation
arr1 = np.array([1,2,3,4,5]) #1D Array
print(arr1)
print(type(arr1)) #Check type

arr2 = np.array([[10,20,30],[40,50,60]]) #2D Array
print(arr2)
print(type(arr2))

arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[6,7,8], [9,10,11],[12,13,14]], [[15,16,17],[19,20,21],[22,23,24]]])
print(arr3)
print(arr3.ndim) #Check numbber of dimensions

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [19 20 21]
  [22 23 24]]]
3


# Array Dimensions
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
An array that has 1-D arrays as its elements is called a 2-D array.
An array that has 2-D arrays (matrices) as its elements is called 3-D array.


In [10]:
arr4 = np.array([1,2,3], ndmin = 4)
print(arr4)


[[[[1 2 3]]]]


In [22]:
print(arr1[0]) #Accessing an element of a 1D array
print("the third element on second row: " , arr2[1,2]) # [row number-1, element number-1]
print("the third element on third row in second array block:", arr3[1,2,2])

#Use NEGATIVE INDEXING to strat from the end
print(arr1[-1]) #outputs -5
print(arr2[0,-1]) #outputs 30


1
the third element on second row:  60
the third element on third row in second array block: 14
5
30


# Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [29]:
#Slicing Arrays 
subArray1D = arr1[1:3] 
print(subArray1D) #outputs the 2nd and 3rd element of 1D Array

subArray2D = arr2[0:2, 1:3] #Accessing the the second and third element in the first and second row
print(subArray2D)
print()
subArray3D = arr3[0:3, 1:3, 2:3] #Accessing all the 2D arrays and then accessing to the third element on the second and third row
print(subArray3D)
print(type(subArray3D))


[2 3]
[[20 30]
 [50 60]]

[[[ 6]
  [ 9]]

 [[11]
  [14]]

 [[21]
  [24]]]
<class 'numpy.ndarray'>


# Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [39]:
print(arr1.dtype) #outputs int

fruits = np.array(["apple","banana","strawberry","pear","watermelon"], dtype = "S")
print(fruits)
print(fruits.dtype)


decimals = np.array([[5.7,10.3,15.4,20.9],[25.5,30.1,35.6,40.7]]) 
wholeNum = decimals.astype("i") #casting elements of the array from double to int 
print(wholeNum)


int64
[b'apple' b'banana' b'strawberry' b'pear' b'watermelon']
|S10
[[ 5 10 15 20]
 [25 30 35 40]]


In [40]:
x = np.array([[[1],[2]],[[3],[4]]])
print(x)

[[[1]
  [2]]

 [[3]
  [4]]]


In [44]:
a=np.array([[2,1],[1,3]])
print(a)
print(a*a)

b=np.array([[3,4],[1,3]])
print(b)
print(b*b)

[[2 1]
 [1 3]]
[[4 1]
 [1 9]]
[[3 4]
 [1 3]]
[[ 9 16]
 [ 1  9]]
