In [1]:
import numpy as np

In [22]:
liste = [[10,20,30],[40,50,60],[70,80,90]]
matrix = np.array(liste)

In [23]:
matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [24]:
matrix[0]

array([10, 20, 30])

In [25]:
print(matrix[0,2])
print(matrix[0][2])

30
30


In [40]:
matrix[0:,2]

array([30, 60, 90])

In [41]:
matrix[0:2,1:]

array([[20, 30],
       [50, 60]])

In [46]:
newList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]
newMatrix = np.array(newList)
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
newMatrix[[1,3]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [49]:
newMatrix[[2,0,3]]

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

# Operations

In [56]:
newArray = np.random.randint(1,100,5)

In [57]:
newArray

array([79, 20, 46, 78, 65])

In [59]:
filteredArray = newArray > 50

In [60]:
newArray[filteredArray]

array([79, 78, 65])

In [61]:
 orderedArray = np.arange(0,10)

In [63]:
orderedArray + orderedArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
orderedArray * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [69]:
np.sqrt(orderedArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])