In [18]:
import numpy as np
a=np.random.randn(4,3) # a.shape = (4, 3)a.shape=(4,3)

b = np.random.randn(1, 3) # b.shape = (1, 3)b.shape=(1,3)

c = a*b
print(c)

[[ 0.46101072  2.23421037 -0.07621505]
 [ 0.82964812 -0.24831979  0.09687347]
 [-0.92218246 -0.14247281 -0.0367425 ]
 [ 0.52053786 -1.24896606  0.08192561]]


In [21]:
x = np.random.randn(8,1)
print(x)
x.reshape(2,2,2) #3D-array

[[ 0.28259466]
 [ 0.20234049]
 [ 0.17694644]
 [-0.1163949 ]
 [-0.13529891]
 [-3.13794791]
 [ 0.76475351]
 [-1.05356077]]


array([[[ 0.28259466,  0.20234049],
        [ 0.17694644, -0.1163949 ]],

       [[-0.13529891, -3.13794791],
        [ 0.76475351, -1.05356077]]])