In [1]:
import numpy as np

In [2]:
arr = np.arange(0,15)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr[5]

5

# Array Slicing

In [5]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [8]:
arr[3:8] = -5 #all elements between 4th and 8th element now equal -5 as value
arr

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
arr2 = np.arange(0,24)

In [10]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
subarr2 = arr2[4:9]

In [12]:
subarr2

array([4, 5, 6, 7, 8])

In [13]:
type(subarr2)

numpy.ndarray

In [14]:
subarr2[:] = 100

In [15]:
subarr2

array([100, 100, 100, 100, 100])

In [16]:
arr2 #change in the value of subbarr2 elements affected arr2

array([  0,   1,   2,   3, 100, 100, 100, 100, 100,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Copy vs View

In [29]:
arr3 = np.arange(0,10)

In [30]:
arr3copy = arr3.copy()

In [31]:
arr3copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
subarr3copy = arr3copy[3:6]

In [33]:
subarr3copy[:] = 100

In [34]:
subarr3copy

array([100, 100, 100])

In [35]:
arr3copy

array([  0,   1,   2, 100, 100, 100,   6,   7,   8,   9])

In [36]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])