# Numpy Array Creation

In [1]:
import numpy as np

# 0-D Arrays

0-D arrays, or Scalars, are the elements in an array.

In [12]:
scalar = np.array(10)
print(type(scalar))
print(scalar)

<class 'numpy.ndarray'>
10


# 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [15]:
arr1D = np.array([1,2,3,4,5])
print(type(arr1D))
print(arr1D)

<class 'numpy.ndarray'>
[1 2 3 4 5]


# 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [9]:
matrix = np.array([[10,20,30],[40,50,60]])
print(matrix)

[[10 20 30]
 [40 50 60]]


# 3-D Arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

# Accessing Elements of an Array

In [17]:
print(arr1D[1])
print(matrix[0][2])

2
30


In [18]:
np.array(matrix)

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
np.array(matrix[0])

array([10, 20, 30])

# Numpy Array Creation Methods

arange

In [22]:
even = np.arange(0,10,2)
even

array([0, 2, 4, 6, 8])

Zeros

In [29]:
np.zeros(10) #creates numpy array with 10 zero's

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

Ones

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

linspace

In [36]:
np.linspace(0,100,5) 
#Her eleman ile bir önceki eleman arasındaki farkı eşit olan array

array([  0.,  25.,  50.,  75., 100.])

eye

In [39]:
np.eye(5)#creates identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])